### ISSUE TITLE
发送聊天快捷键改回Enter，主流聊天软件都是这个快捷键，如果换行参照微信Enter

### ISSUE THREAD

**Issue by Biubiu99999** [AICCOF/chatmoss-ui#1]
如果换行参照微信Enter+shift,每次聊天还得鼠标点一下，非常不方便，体验不好（1344187587）

**Comment by zhukunpenglinyutong** [comment]
<img width="557" alt="image" src="https://user-images.githubusercontent.com/31264015/227762616-8e3ddaf0-c4ab-446b-a18b-81f07042da29.png">

最新的v1.5.0版本已经支持了
