### ISSUE TITLE
有BUG

### ISSUE THREAD

**Issue by Hefengshun** [AICCOF/chatmoss-ui#110]
因为项目多所以vsCode多开 貌似一个code上使用  扣除的是多个code字数的和  还比4个code  相当于在一个code上搜索消耗4倍

**Comment by zhukunpenglinyutong** [comment]
并不是的，字符数消耗是根据token来的，并不是一个汉字就是一个字符，可能一个成语四个字就要消耗几十个字符，这里字符消耗，是根据OpenAI返回给我们的token消耗回调来的，比较准确
