### ISSUE TITLE
vscode 插件 UI 问题

### ISSUE THREAD

**Issue by jsyt** [AICCOF/chatmoss-ui#112]
Visual Studio Code - Insiders
版本: 1.78.0-insider
提交: b19017cea80b6157aa8214c984a70022e77526f2
日期: 2023-04-21T05:39:53.263Z (2 天前)
Electron: 22.4.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.2.0
沙盒化: Yes

<img width="578" alt="image" src="https://user-images.githubusercontent.com/36355189/233896931-46d49e47-005f-4eb0-a436-292fa1f99481.png">

**Comment by zhukunpenglinyutong** [comment]
收到，马上优化
