### ISSUE TITLE
恢复对话界面的问答可删除功能，

### ISSUE THREAD

**Issue by Alex-zry-2333** [AICCOF/chatmoss-ui#131]
当出现回答错误或者提问不详细时，希望通过删除对应内容来保证整体的整洁干净。

我使用它来进行发散思维的整理，但是去掉删除功能之后，我不能将一些我不需要的发散内容剔除，影响我继续顺着某条线路继续探究的想法。

**Comment by zhukunpenglinyutong** [comment]
此功能短期可能无法实现
