### ISSUE TITLE
关于ChatMoss主题设定切换问题，主题生效了，但是Switch开关状态没有切换。

### ISSUE THREAD

**Issue by LLLike27** [AICCOF/chatmoss-ui#151]
![1684462124420](https://github.com/AICCOF/chatmoss-ui/assets/93822826/a7d81a03-cec2-4462-8f5e-16cacfafac2f)
![1684462147562](https://github.com/AICCOF/chatmoss-ui/assets/93822826/06d95283-a43e-4c5e-a499-99ece1add433)

**Comment by zhukunpenglinyutong** [comment]
收到：近期v4.0版本会对UI进行改版，敬请期待
