### ISSUE TITLE
账号无法登陆， 没有任何提示

### ISSUE THREAD

**Issue by jamshid-007** [AICCOF/chatmoss-ui#154]
前天开始账号现在没有登陆， 需要重新登陆
输入注册的邮箱密码无任何提示
重置密码也无法接受到相应的邮件。 
账号名: gvc8127@163.com

![Capture](https://github.com/AICCOF/chatmoss-ui/assets/129260961/db6238c4-1df6-4c0f-83f3-316bd2a90993)

**Comment by zhukunpenglinyutong** [comment]
如果是window端，可以先试试用其他端，window在有的地区DNS解决有问题，还未解决
