### ISSUE TITLE
回答中字体变化问题

### ISSUE THREAD

**Issue by 1180300125** [AICCOF/chatmoss-ui#156]
我提出了一个关于正则表达式的问题，给出的回答里包含^和$字符，这两个字符会导致识别为其他字体，影响阅读。
![47ab413ca6ece59ac6f43984dfa2020](https://github.com/AICCOF/chatmoss-ui/assets/61404397/1f8d5d5a-83b4-46a8-9371-c099d24d1867)

**Comment by zhukunpenglinyutong** [comment]
你可以让其以 代码片段的方式输出即可解决此问题，目前看起来是以md的格式输出了
