### ISSUE TITLE
突然无法正常使用

### ISSUE THREAD

**Issue by Link-Who** [AICCOF/chatmoss-ui#169]
在未登录状态下，一直显示API key invalid,我上openAI生成了新的，输入，也还是一样，之前一直使用正常

**Comment by zhukunpenglinyutong** [comment]
你这是账号api到期了，即使新建无数个，也都无法使用，以为到期的是账号下所有的api使用资格

**Comment by Link-Who** [comment]
> 

懂了，谢谢！
