### ISSUE TITLE
增加省流模式，降低moss消耗

### ISSUE THREAD

**Issue by zhukunpenglinyutong** [AICCOF/chatmoss-ui#2]
上下文需要传递，提问和回答的所有内容，这些都会算到moss消耗中，随着对话的增加moss数量也大幅度增加

所以增加一个 滑动按钮，用于用户随时切换是否传输上下文，不传输上下文即为省流模式

预计发布版本：v1.5.2

**Comment by qqlcx5** [comment]
提问买卖股票的最佳时机，直接把免费干没了，我记得不是一天可以提问50次？

**Comment by zhukunpenglinyutong** [comment]
v1.5.2版本已发布
