### ISSUE TITLE
对话有时无法识别

### ISSUE THREAD

**Issue by isooc** [AICCOF/chatmoss-ui#32]
![image](https://user-images.githubusercontent.com/51506350/229086572-8340f793-0c53-407b-8c38-e1baced90ff6.png)
目前可以通过点击刷新按钮或开启新对话实现，但会失去上下文联系

**Comment by zhukunpenglinyutong** [comment]
收到，马上更改

**Comment by hanjie-chen** [comment]
我也有相同的情况，当对话次数过多时，就会失去上下文联系，需要每次手动刷新。而且手动刷新次数过多之后chatMoss将会失去之前对话所获得的信息

**Comment by zhukunpenglinyutong** [comment]
可以试试v3.0新版，支持了无限上下文模式
