### ISSUE TITLE
开启联网功能之后，没必要每个回答都去搜索互联网吧

### ISSUE THREAD

**Issue by hanjie-chen** [AICCOF/chatmoss-ui#37]
<img width="545" alt="截屏2023-04-04 22 52 04" src="https://user-images.githubusercontent.com/56195905/229832019-bb4ae2c6-3cbc-473b-a6f6-5529b5307f75.png">

**Comment by zhukunpenglinyutong** [comment]
目前还没办法智能的分析，对话是否需要联网搜索，现在还需要手动开关

**Comment by hanjie-chen** [comment]
感谢告知
