### ISSUE TITLE
左右栏同步问题

### ISSUE THREAD

**Issue by KujoJotaroI** [AICCOF/chatmoss-ui#47]
在代码上直接右键点击的内容（解释 优化等）无法和左侧直接点击的内容同步 如图所示
希望可以做到两边同步
![image](https://user-images.githubusercontent.com/130072776/230409880-640012e5-be80-40a2-a41b-9e1359b81e8d.png)

**Comment by zhukunpenglinyutong** [comment]
v2.1.10发布
