### ISSUE TITLE
ChatMoss UI 升级

### ISSUE THREAD

**Issue by zhukunpenglinyutong** [AICCOF/chatmoss-ui#6]
对ChatMoss UI 和 交互 进行大的升级，更加方便用户使用

预计发布版本：v1.7.0+

**Comment by Jairwin-L** [comment]
建议UI组件库可以使用[antdv](https://antdv.com/components/overview)

**Comment by zhukunpenglinyutong** [comment]
> 

会考虑的

**Comment by zhukunpenglinyutong** [comment]
v2.0.0版本已升级UI
