### ISSUE TITLE
无法注册

### ISSUE THREAD

**Issue by ITWhx** [AICCOF/chatmoss-ui#61]

**Comment by ITWhx** [comment]
无法注册，点击发送验证码无效

**Comment by zhukunpenglinyutong** [comment]
升级v2.1.1最新版本后可以，更换了服务器地址

**Comment by python-qiang** [comment]
我已经升级到了v2.1.2版本，但还是无法注册，收不到验证码，而且上面警告的info icon没有详细的message
![image](https://user-images.githubusercontent.com/104023670/231045844-03fff81d-2c9d-493f-8893-72957a08f102.png)
