### ISSUE TITLE
English localisation?

### ISSUE THREAD

**Issue by ward-anomalous** [AICCOF/chatmoss-ui#67]
This extension looks amazing, and I see there's already an English localisation for it ([src/locales/en-US.ts](https://github.com/AICCOF/chatmoss-ui/blob/e44071f6161573c6109da1ef1297422689d49fbb/src/locales/en-US.ts)), but no in-app option to switch to it. I would be happy if a setting for localisation could be added at some point! :)

**Comment by zhukunpenglinyutong** [comment]
受众针对汉语
