### ISSUE TITLE
vscode插件  弹出helloword就没有必要了吧

### ISSUE THREAD

**Issue by dbeenlee** [AICCOF/chatmoss-ui#75]
vscode插件  每次打开软件或者切换工作区都会弹出  
![image](https://user-images.githubusercontent.com/4352949/231924856-7f814ed9-cc01-4abf-9286-ce2a75f8eb3a.png)

**Comment by you-hengh** [comment]
同意, 这个弹窗会挡住 chatmoss的输入框 属实没必要

**Comment by zhukunpenglinyutong** [comment]
已经开始优化，v2.1.9版本更新
