### ISSUE TITLE
体验优化-输入法输入问题优化

### ISSUE THREAD

**Issue by 624515059** [AICCOF/chatmoss-ui#82]
电脑：mac
输入法：搜狗输入法
优化问题描述：
输入法中文模式下，如果输入带有英文单词的问题只需要按回车就可以打印到键盘上，不过第一次打印成功，第二次则会触发问题的发送选项，体验不好。
比如输入问题：【java是js吗】，java按回车正确打印到input中，输入js按回车时，则直接触发了发送功能

**Comment by zhukunpenglinyutong** [comment]
收到，近期会进行优化
