### ISSUE TITLE
不够智能

### ISSUE THREAD

**Issue by MasterYoda999** [AICCOF/chatmoss-ui#89]
实现一个拖拽功能的vue自定义指令叫v-drag

以下是一个实现拖拽功能的 Vue 自定义指令 v-drag 的示例代码：

复制
<template>
  <div v-drag>我可以拖动</div>
</template>

<script>
export default {
  directives: {
    drag: {
      mounted(el) {
        el.addEventListener('mousedown', handleMouseDown);
        el.addEventListener('mousemove', handleMouseMove);
        el.addEventListener('mouseup', handleMouseUp);
      },
      unmounted(el) {
        el.removeEventListener('mousedown', handleMouseDown);
        el.removeEventListener('mousemove', handleMouseMove);
        el.removeEventListener('mouseup', handleMouseUp);
      },
    },
  },
};

let isDragging = false;
let startX = 0;
let startY = 0;

function handleMouseDown(event) {
  isDragging = true;
  startX = event.clientX;
  startY = event.clientY;
}

function handleMouseMove(event) {
  if (isDragging) {
    const deltaX = event.clientX - startX;
    const deltaY = event.clientY - startY;
    event.target.style.transform = `translate(${deltaX}px, ${deltaY}px)`;
  }
}

function handleMouseUp() {
  isDragging = false;
}
</script>
在上面的代码中，我们定义了一个名为 drag 的自定义指令，并在 mounted 钩子中添加了鼠标事件监听器。当鼠标按下时，将 isDragging 设置为 true，并记录起始位置 startX 和 startY。当鼠标移动时，如果 isDragging 为 true，则计算出鼠标移动的距离，并将元素的位置设置为相对于起始位置的偏移量。当鼠标抬起时，将 isDragging 设置为 false。

我们可以在模板中使用 v-drag 指令来启用拖拽功能。当用户按下鼠标并移动时，元素会跟随鼠标移动，直到鼠标抬起为止。

**Comment by zhukunpenglinyutong** [comment]
可以试试v3.0新版，支持了无限上下文模式
