### ISSUE TITLE
上下文开启似乎也不认上下文，每次输入都会先返回“How can I help you today?”，点击刷新才回复问题

### ISSUE THREAD

**Issue by imissfm** [AICCOF/chatmoss-ui#98]
上下文开启似乎也不认上下文，每次输入都会先返回“How can I help you today?”或者“Hello! How can I assist you today?”，点击刷新才回复问题。所以上下文老是断，连不起来。

**Comment by xiaoping6688** [comment]
我也是

**Comment by zhukunpenglinyutong** [comment]
最新版本增加了无限上下文功能，此问题已修复
